import { NextRequest, NextResponse } from 'next/server'

interface ExportApp {
  app_name: string
  app_type: string
  description: string
  is_complete: boolean
  reuse_percentage: number
  missing_files_count: number
  missing_files: string[]
  technologies: string[]
  difficulty_level: string
  ai_explanation: string
}

export async function POST(request: NextRequest) {
  try {
    const { app } = (await request.json()) as { app: ExportApp }

    // Generate HTML content for PDF
    const htmlContent = generateHTML(app)

    // Use a PDF generation service (we'll use a simple approach for now)
    // In production, use jsPDF or similar library
    const pdfContent = generatePDFContent(htmlContent)

    return new NextResponse(pdfContent, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${app.app_name.toLowerCase().replace(/\s+/g, '-')}-report.pdf"`,
      },
    })
  } catch (error) {
    console.error('Error generating PDF:', error)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}

function generateHTML(app: ExportApp): string {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
          h1 { color: #000; border-bottom: 3px solid #000; padding-bottom: 10px; }
          h2 { color: #555; margin-top: 20px; }
          .section { margin: 20px 0; }
          .badge { display: inline-block; padding: 5px 10px; background: #f0f0f0; border-radius: 4px; margin: 5px 5px 5px 0; font-size: 12px; }
          .complete { background: #d4edda; color: #155724; }
          .partial { background: #fff3cd; color: #856404; }
          table { width: 100%; border-collapse: collapse; margin: 10px 0; }
          th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
          th { background: #f5f5f5; }
          ul { margin: 10px 0; padding-left: 20px; }
          li { margin: 5px 0; }
        </style>
      </head>
      <body>
        <h1>${app.app_name}</h1>
        
        <div class="section">
          <h2>Overview</h2>
          <p><strong>Type:</strong> ${app.app_type}</p>
          <p><strong>Description:</strong> ${app.description}</p>
          <p><strong>Status:</strong> <span class="badge ${app.is_complete ? 'complete' : 'partial'}">${app.is_complete ? 'Complete' : 'Partial'}</span></p>
        </div>

        <div class="section">
          <h2>Key Metrics</h2>
          <table>
            <tr>
              <th>Metric</th>
              <th>Value</th>
            </tr>
            <tr>
              <td>Reusable Code</td>
              <td>${app.reuse_percentage}%</td>
            </tr>
            <tr>
              <td>Difficulty Level</td>
              <td>${app.difficulty_level}</td>
            </tr>
            <tr>
              <td>Missing Files</td>
              <td>${app.missing_files_count}</td>
            </tr>
          </table>
        </div>

        ${app.technologies.length > 0 ? `
          <div class="section">
            <h2>Technologies</h2>
            <div>${app.technologies.map((t: string) => `<span class="badge">${t}</span>`).join('')}</div>
          </div>
        ` : ''}

        ${app.missing_files.length > 0 ? `
          <div class="section">
            <h2>Missing Files</h2>
            <ul>
              ${app.missing_files.map((f: string) => `<li>${f}</li>`).join('')}
            </ul>
          </div>
        ` : ''}

        <div class="section">
          <h2>Analysis & Explanation</h2>
          <p>${app.ai_explanation}</p>
        </div>

        <div class="section">
          <h2>Getting Started</h2>
          <ol>
            <li>Create a new repository</li>
            <li>Clone the reusable files from identified source repositories</li>
            <li>Install all dependencies</li>
            <li>Add ${app.missing_files_count} missing files</li>
            <li>Test thoroughly</li>
            <li>Deploy to production</li>
          </ol>
        </div>

        <p style="margin-top: 40px; color: #999; font-size: 12px;">
          Generated by RepoFuse on ${new Date().toLocaleDateString()}
        </p>
      </body>
    </html>
  `
}

function generatePDFContent(html: string): Buffer {
  // For production, use a proper PDF library like jsPDF or pdfkit
  // For now, return a simple text representation
  const text = html
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')

  return Buffer.from(text, 'utf-8')
}
