#!/usr/bin/env node

const http = require("http");
const fs = require("fs");
const path = require("path");
const url = require("url");
const { scanProject } = require("./index");

const PORT = process.env.EAF_PORT || 4800;

function parseBody(req) {
  return new Promise((resolve, reject) => {
    let body = "";
    req.on("data", (chunk) => (body += chunk));
    req.on("end", () => {
      try {
        resolve(JSON.parse(body));
      } catch {
        resolve({});
      }
    });
    req.on("error", reject);
  });
}

function json(res, data, status = 200) {
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
  });
  res.end(JSON.stringify(data));
}

function serveFile(res, filePath, contentType) {
  try {
    const content = fs.readFileSync(filePath, "utf-8");
    res.writeHead(200, { "Content-Type": contentType });
    res.end(content);
  } catch {
    res.writeHead(404);
    res.end("Not found");
  }
}

function generateEnvFile(envVars, services, userValues = {}) {
  const lines = [];
  lines.push("# Generated by env-agent-finder");
  lines.push(`# ${new Date().toISOString()}`);
  lines.push("");

  const varServiceMap = {};
  for (const svc of services) {
    for (const v of svc.requiredEnvVars || []) {
      varServiceMap[v] = svc.name;
    }
  }

  const grouped = new Map();
  for (const v of envVars) {
    const svc = varServiceMap[v.name] || v.service || "Other";
    if (!grouped.has(svc)) grouped.set(svc, []);
    grouped.get(svc).push(v);
  }

  for (const [service, vars] of grouped) {
    lines.push(`# ${service}`);
    for (const v of vars) {
      const value = userValues[v.name] || v.value || "";
      lines.push(`${v.name}=${value}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

const server = http.createServer(async (req, res) => {
  const parsed = url.parse(req.url, true);
  const pathname = parsed.pathname;

  if (req.method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    });
    res.end();
    return;
  }

  if (pathname === "/" && req.method === "GET") {
    serveFile(res, path.join(__dirname, "app.html"), "text/html");
    return;
  }

  if (pathname === "/api/scan" && req.method === "POST") {
    const body = await parseBody(req);
    const targetDir = body.path;

    if (!targetDir) {
      return json(res, { error: "Missing 'path' field" }, 400);
    }

    const resolved = path.resolve(targetDir);
    if (!fs.existsSync(resolved)) {
      return json(res, { error: `Directory not found: ${resolved}` }, 404);
    }

    try {
      const report = await scanProject(resolved);
      return json(res, report);
    } catch (err) {
      return json(res, { error: err.message }, 500);
    }
  }

  if (pathname === "/api/generate" && req.method === "POST") {
    const body = await parseBody(req);
    const { envVars, services, userValues } = body;

    if (!envVars) {
      return json(res, { error: "Missing scan data" }, 400);
    }

    const content = generateEnvFile(envVars, services || [], userValues || {});
    return json(res, { content, filename: ".env.local" });
  }

  if (pathname === "/api/save" && req.method === "POST") {
    const body = await parseBody(req);
    const { targetDir, envVars, services, userValues } = body;

    if (!targetDir || !envVars) {
      return json(res, { error: "Missing required fields" }, 400);
    }

    const resolved = path.resolve(targetDir);
    const envPath = path.join(resolved, ".env.local");
    const content = generateEnvFile(envVars, services || [], userValues || {});

    try {
      fs.writeFileSync(envPath, content, "utf-8");
      return json(res, { success: true, path: envPath });
    } catch (err) {
      return json(res, { error: err.message }, 500);
    }
  }

  res.writeHead(404);
  res.end("Not found");
});

server.listen(PORT, () => {
  console.log("");
  console.log("═".repeat(50));
  console.log("  ENV AGENT FINDER — Web App");
  console.log("═".repeat(50));
  console.log("");
  console.log(`  🌐 Open in browser: http://localhost:${PORT}`);
  console.log("");
  console.log("  Press Ctrl+C to stop");
  console.log("═".repeat(50));
  console.log("");
});
